print('====exponentiation====')
print(2 ** 3)
print(2 ** 3.)
print('====multiplication====')
print(2 * 3)
print(2 * 3.)
print('====division====')
print(6 / 3)
print(6 / 3.)
print('====integer division====')
print(6 // 3)
print(6 // 3.)
print('====remainder (modulo)====')
print(14 % 4)
print('====addition====')
print(-4 + 4)
print(-4. + 8)
print('====subtraction====')
print(-4 - 4)
print(4. - 8)
